class DB_QUERY:

    ALL_ITEMS_WITH_FILTER = '''
        Select * from {container_name} 
        where {container_name}.{space_id_field} = "{space_id}"
        and {container_name}.{instance_list_field} = false
    '''
    ITEMS_WITH_FILTER_INSTANCE = '''
        Select * from {container_name} 
        where {container_name}.{instance_id_field} = "{instance_id}"
    '''

    ALL_DOC_TYPES = '''
        Select * from {container_name} 
        where {container_name}.{space_id_field} = "{space_id}"
    '''

    ALL_DOCS_FOR_RAG = '''
        Select * from {container_name} 
        where {container_name}.{space_id_field} = "{space_id}" 
        and {container_name}.{rag_flag_field} = true
        and {container_name}.{is_instance_doc_field} = false
    '''

    ALL_INSTANCE_DOCS_FOR_RAG = '''
        Select * from {container_name} 
        where {container_name}.{instance_id_field} = "{instance_id}" 
        and {container_name}.{rag_flag_field} = true
    '''

    RESPONSE_TEMPLATE_DOC = '''
        Select * from {container_name} 
        where {container_name}.{space_id_field} = "{space_id}" and {container_name}.{doc_id_field} = "{doc_id}" 
    '''

    DOCS_BY_ID_LIST = '''
        Select * from {container_name} 
        where {container_name}.{doc_type_id_field} IN {doc_type_id_list}
    '''

    ALL_ITEMS_FOR_OPTIMUM_FLAG = '''
        Select * from {container_name} 
        where {container_name}.{space_id_field} = "{space_id}" and {container_name}.{flag_field} = true
    '''

    SPACE_FOR_USER_QUERY = '''
        Select * from {container_name} 
        where {container_name}.{insatnce_id_field} = "{instance_id}"
    '''

    INSTANCE_PROMPT_LIST = '''
        Select * from {container_name} 
        where {container_name}.{instance_flag_field} = true
        and {container_name}.{instance_id_field} = "{instance_id}" 
    '''

    RESPONSE_DOC = '''
        Select * from {container_name} 
        where {container_name}.{instance_id_field} = "{instance_id}" 
        and {container_name}.{response_flag_field} = true
    '''
    GET_DOC_QUERY_FILTER = '''
        Select * from {container_name} 
        where {container_name}.{space_id_field} = "{space_id}"
    '''

    PERSISTENT_DOC_TYPES = '''
        Select * from {container_name} 
        where ({container_name}.{doc_type_level_field} = 0 AND ARRAY_CONTAINS({container_name}.{linked_assistants_field},"{space_id}", true) )
        OR ({container_name}.{doc_type_level_field} = 1 AND {container_name}.{space_id_field} = "{space_id}")
    '''

    PERSISTENT_DOCS = '''
        Select * from {container_name} 
        where {container_name}.{doc_type_field} IN ({doc_types})
        and {container_name}.{rag_flag_field} = true
    '''

    GET_VARIABLE_SET_ITEM = '''
        Select * from {container_name} 
        where {container_name}.{space_id_field} = "{space_id}"
    '''
    
    DOC_TYPES_FOR_SPACE = '''
        Select * from {container_name} 
        where ({container_name}.{doc_type_level_field} = 0 AND ARRAY_CONTAINS({container_name}.{linked_assistants_field},"{space_id}", true) )
        OR ({container_name}.{space_id_field} = "{space_id}")    
    '''
    
    STUDIO_LEVEL_DOC_TYPES = '''
        Select * from {container_name} 
        where {container_name}.{doc_type_level_field} = 0
    '''
    
class AI_SEARCH:
    INDEX_NAME = 'chatifc-aistudio-1'
    MODEL_TOKEN_LIMIT = {
                'gpt-4': 128000,
                'gpt-4o': 128000,
                'gpt-35-turbo-16k': 16384
            }
    MAX_TOKEN_LIMIT_MESSAGE = '''Permissible token limit breached for the LLM.
    Tokens: {numofToken}
    Tokens permissible for the LLM: {tokenLimit}
    Lower the top K value in the LLM settings or change the LLM.Please contact the admin for this Assistant'''
    VARIABLE_SET_REQUIRED_MESSAGE ='This section is blank due to missing required variables. For better document co-creation, please define these variables(s):'
class ENV_SWITCH:
    LOG_STORE = 'LOCAL'
    # LOG_STORE = 'AZURE_APP_INSIGHTS'

class URL:
    OAUTH2_AUTH = 'https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/authorize'
    OAUTH2_TOKEN = 'https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token'
    JWKS_URI = 'https://login.microsoftonline.com/{tenant_id}/discovery/v2.0/keys'

class MSG:
    PARTIAL_CONTENT = 'Partial content generated for this section due to missing document types. For better document co-creation, please upload relevant document type(s): {}.'
    NO_CONTENT = 'This section is blank due to missing document types. For better document co-creation, please upload relevant document type(s): {}.'
    FETCH_FAILURE = 'Failed to fetch all items from DB'
    AI_DISCLAIMER = 'Note: This document is generated by AI. AI-generated content may be incorrect.'

class SECRETS:
    KEYS = ['COSMOSDB_KEY', 'AZURE_AISEARCH_KEY', 'AZURE_OPENAI_API_KEY']

class STATUS_MSG:
    IN_PROGRESS = 'Response generation is in progress.'
    COMPLETED = 'Response generated.'

class MISC:
    AI_DISCLAIMER_RBG = (70, 132, 232)
    MISSING_CONTENT_RBG = (128, 128, 128)
    DOC_STYLE_LB = 'List Bullet'
    DOC_STYLE_LN = 'List Number'
    DOC_STYLE_TB = 'Table Grid'
    DOC_TYPE_LEVEL_MAP = {
        0: 'studio',
        1: 'assistant',
        2: 'user-defined'
    }
